### ISSUE TITLE
Primary sidebar is not getting appropriate left or right class

### ISSUE THREAD

**Issue by carrieforde** [carrieforde/Alcatraz#11]
Currently, the primary sidebar hangs out at the bottom of the page because it is not getting either the `.left-sidebar` or `.right-sidebar` class.

**Comment by BraadMartin** [comment]
Hmm, both Left and Right sidebar, set globally and at the page level, are working great for me on the latest master. The class gets added to the body, not the sidebar itself.

We can add it to the sidebar itself also, and I know the WordPress CSS coding standards generally say to put the class on the thing rather than the wrapper, but in this case and with most of our global theme options I like having them on the body because then we can use them across all elements in the body, they all stay together, they are only ever defined once, and it's easier to change them on the fly with JS (which we'll soon be doing in the Customizer wherever we can). Plus WordPress adds its classes for what page we're displaying on the body, which allows us to chain the selectors for all of our theme options with the WordPress classes for something like

``` css
.primary-sidebar { 
   background-color: #aaa; 
}
.right-sidebar.category-music.has-page-banner .primary-sidebar { 
   background-color: #ccc; 
}
```
